const routerx = require('express-promise-router');
const authController = require('../controllers/authController');
const rewardController = require('../controllers/rewardController');

const Router = routerx();

Router.post('/google-login', authController.userGoogleLogin);
Router.post('/metamask-login', authController.metamaskLogin);
Router.post('/email-login', authController.emailLogin);
Router.post('/verifyEmailCode', authController.verifyEmailCode);
Router.post('/updateProfileSet', authController.updateProfileSet);
Router.post('/getMyBalance', authController.getMyBalance);
Router.post('/getMyBalances', authController.getMyBalances);
Router.post('/getAuthData', authController.getAuthData);
Router.post('/getProfileData', authController.getProfileData);
Router.post('/followUser', authController.followUser);
Router.post('/unFollowUser', authController.unFollowUser);
Router.post('/getDepositBonus', authController.getDepositBonus);
Router.post('/getBetHistoryData', authController.getBetHistoryData);
Router.post('/updateCurrency', authController.updateCurrency);
Router.post('/updateProfileHistory', authController.updateProfileHistory);
Router.post('/updateUserGameSetting', authController.updateUserGameSetting);
Router.post('/getSeedData', authController.getSeedData);
Router.post('/updateClientSeed', authController.updateClientSeed);
Router.post('/updateServerSeed', authController.updateServerSeed);
Router.post('/getLevelData', authController.getLevelData);
Router.post('/getAvailableGames', authController.getAvailableGames);
Router.post('/getBannerText', authController.getBannerText);
Router.post('/getPrivacyData', authController.getPrivacyData);
Router.post('/updatePrivacyData', authController.updatePrivacyData);
Router.post('/getCampaignCode', authController.getCampaignCode);
Router.post('/getCampaignData', authController.getCampaignData);
Router.post('/claimCampaignAmount', authController.claimCampaignAmount);
Router.post('/getUnlockBalance', authController.getUnlockBalance);
Router.post('/getWargerBalance', authController.getWargerBalance);
Router.post('/claimLockedBalance', authController.claimLockedBalance);
Router.post('/getSpinCount', rewardController.getSpinCount);
Router.post('/updateSpinCount', rewardController.updateSpinCount);
Router.post('/getTournamentList', authController.getTournamentList);
Router.post('/participateTournament', authController.participateTournament);
Router.post('/getAffiliateUsersData', authController.getAffiliateUsersData);
Router.post('/getAffiliateEarningData', authController.getAffiliateEarningData);
Router.post('/getTournamentWargerDetail', authController.getTournamentWargerDetail);
Router.post('/getCampaignList', authController.getCampaignList);
Router.post('/addCampaignList', authController.addCampaignList);
Router.post('/getCampaignDetail', authController.getCampaignDetail);
Router.post('/getTransactionHistory', authController.getTransactionHistory);

module.exports = Router;