exports.ROUND_STATUS = {
    COUNTDOWN: 0,
    WAITING: 1,
    STARTED: 2,
    FINISHED: 3,
    COMPLETED: 4
};

exports.ROUND_DATA = {
    TIME_COUNTDOWN: 10,
    TIME_NEWROUND: 2,
    INTERVAL_COUNTDOWN: 50,
    INTERVAL_RUNNING: 50,
    INTERVAL_CONFIRMING: 50,
    INITIAL_PAYOUT: 1,
    GROWTH_FACTOR: 1.05 //5% per seconds
};